In [1]:
import pandas as pd
import numpy as np

s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
s=pd.Series([10,20,30], index=['a','b','c'])
print(s)
print(s["a"])
# print(s[0])  ye nas colab pe chalega but vscode pe nahi chalega verion ka issue hai

a    10
b    20
c    30
dtype: int64
10

In [3]:
data={"Math": 90, "Physics": 85, "Chemistry": 88}
marks=pd.Series(data)
print(data)    #this will print the dictionary with keys and values
print(marks)   #this will print the series with index and values

{'Math': 90, 'Physics': 85, 'Chemistry': 88}
Math         90
Physics      85
Chemistry    88
dtype: int64

In [4]:
# DataFrame in Pandas

data={"Name": ["Aman", "Krish", "Karan"],
      "Age": [22, 23, 21],
      "Marks": [85, 90, 88]
}
print(data)    #this will print the dictionary with keys and values
marks=pd.DataFrame(data)
print(marks)   #Pandas will convert the dictionary into a DataFrame with columns as keys and values as rows(starting from 0 index)

type(data)    #this will print the type of data which is dictionary

{'Name': ['Aman', 'Krish', 'Karan'], 'Age': [22, 23, 21], 'Marks': [85, 90, 88]}
    Name  Age  Marks
0   Aman   22     85
1  Krish   23     90
2  Karan   21     88

dict

In [5]:
# We can also add custom index in pandas DataFrame
marks=pd.DataFrame(data, index=['Student1','Student2','Student3'])
print(marks)   #Pandas will convert the dictionary into a DataFrame with columns as keys and values as rows.

           Name  Age  Marks
Student1   Aman   22     85
Student2  Krish   23     90
Student3  Karan   21     88

In [6]:
marks.set_index("Name", inplace=True)   #If we are setting iplace=True, then it will modify the original DataFrame, otherwise it will return a new DataFrame with the new index.
print(marks)   #Now the index of the DataFrame is set to the "Name" column, and the original index is replaced by the new index.

       Age  Marks
Name
Aman    22     85
Krish   23     90
Karan   21     88

In [7]:
df=pd.DataFrame({
    "Name": ["Aman", "Krish", "Karan"],
    "Age": [22, 23, 21],
    "Marks": [85, 90, 88]
})
print(df)

    Name  Age  Marks
0   Aman   22     85
1  Krish   23     90
2  Karan   21     88

In [8]:
df.head()  #As the number of rows is less than 5, So the output of both df head and df tail will be identical.

    Name  Age  Marks
0   Aman   22     85
1  Krish   23     90
2  Karan   21     88

In [9]:
df.tail()  #As the number of rows is less than 5, So the output of both df head and df tail will be identical.

    Name  Age  Marks
0   Aman   22     85
1  Krish   23     90
2  Karan   21     88

In [10]:
df=pd.DataFrame({
    "Name": ["Aman", "Krish", "Karan", "Shubham", "Rohit", "Virat"],
    "Age": [22, 23, 21, 22, 25, 26],
    "Marks": [85, 90, 88, 90, 56, 70]
})

In [11]:
df.head(2)   #this will print the first 2 rows of the DataFrame

    Name  Age  Marks
0   Aman   22     85
1  Krish   23     90

In [12]:
df.tail(2)   #this will print the last 2 rows of the DataFrame

    Name  Age  Marks
4  Rohit   25     56
5  Virat   26     70

In [13]:
df.shape   #this will print the shape of the DataFrame in the form of (number of rows, number of columns)

(6, 3)

In [14]:
df.columns   #this will print the column names of the DataFrame in the form of Index object

Index(['Name', 'Age', 'Marks'], dtype='str')

In [15]:
df.info()   #this will print the information about the DataFrame such as number of non-null values, data types of columns, memory usage etc.

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     6 non-null      int64
 2   Marks   6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes

In [16]:
df.describe()   #this will print the statistical summary of the DataFrame such as count, mean, std, min, 25%, 50%, 75% and max values for each numerical column.

             Age      Marks
count   6.000000   6.000000
mean   23.166667  79.833333
std     1.940790  13.891244
min    21.000000  56.000000
25%    22.000000  73.750000
50%    22.500000  86.500000
75%    24.500000  89.500000
max    26.000000  90.000000

Selecting the Data

In [17]:
# Selecting the Data
df["Name"]   #this will print the "Name" column of the DataFrame

0       Aman
1      Krish
2      Karan
3    Shubham
4      Rohit
5      Virat
Name: Name, dtype: str

In [18]:
df[["Name", "Marks"]]   #this will print the "Name" and "Marks" columns of the DataFrame

      Name  Marks
0     Aman     85
1    Krish     90
2    Karan     88
3  Shubham     90
4    Rohit     56
5    Virat     70

Filtering in Pandas

In [19]:
# Filtering in Pandas
df[df["Marks"] > 85]   #this will print the rows of the DataFrame where the "Marks" column has values greater than 85

      Name  Age  Marks
1    Krish   23     90
2    Karan   21     88
3  Shubham   22     90

In [20]:
df[(df["Age"] > 21) & (df["Marks"] > 85)]   #this will print the rows of the DataFrame where the "Age" column has values greater than 21 and "Marks" column has values greater than 85

      Name  Age  Marks
1    Krish   23     90
3  Shubham   22     90

Sorting + Value Counts

In [21]:
df.sort_values("Marks")   #this will sort the DataFrame based on the "Marks" column in ascending order. By default, it sorts in ascending order.

      Name  Age  Marks
4    Rohit   25     56
5    Virat   26     70
0     Aman   22     85
2    Karan   21     88
3  Shubham   22     90
1    Krish   23     90

In [22]:
df.sort_values("Marks", ascending=False)   #this will sort the DataFrame based on the "Marks" column in descending order. If we want to sort in ascending order, we can set ascending=True.

      Name  Age  Marks
1    Krish   23     90
3  Shubham   22     90
2    Karan   21     88
0     Aman   22     85
5    Virat   26     70
4    Rohit   25     56

In [23]:
df["Age"].value_counts()   #this will print the count of unique values in the "Age" column of the DataFrame. It will return a Series with index as unique values and values as their counts.

Age
22    2
23    1
21    1
25    1
26    1
Name: count, dtype: int64

In [24]:
# Update the dataset with null values
df=pd.DataFrame({
    "Name": ["Aman", "Saurav", "Karan", "Shubham", None, "Sameer"],
    "Age": [22, 23, None, 22, 25, 26],
    "Marks": [85, None, 88, 90, 56, None]
})
print(df)

      Name   Age  Marks
0     Aman  22.0   85.0
1   Saurav  23.0    NaN
2    Karan   NaN   88.0
3  Shubham  22.0   90.0
4      NaN  25.0   56.0
5   Sameer  26.0    NaN

In [25]:
df.isnull()  #Checking the missing values

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4   True  False  False
5  False  False   True

In [26]:
df.isnull().sum()  #Counting the missing values

Name     1
Age      1
Marks    2
dtype: int64

In [27]:
df.dropna()  #Dropping the rows with missing values

      Name   Age  Marks
0     Aman  22.0   85.0
3  Shubham  22.0   90.0

In [28]:
cleaned_data=df.dropna()  #Storing the cleaned data in a new variable
print(cleaned_data)

      Name   Age  Marks
0     Aman  22.0   85.0
3  Shubham  22.0   90.0

Pandas Exercise 1

In [29]:
# Refrence Table: This is the raw data provided by the admin
# Name [Aman Saurav Karan Shubham Abhishek Missing Sameer]
# Age [22 23 Missing 22 25 24 26]
# Marks [85 Missing 88 90 56 72 Missing]
# Subject [Math Physics Math Chemistry Math Physics Chemistry]
# Note: "Missing" indicates data was not captured(NaN/None).

import pandas as pd
import numpy as np

# Create DataFrame
data = {
    "Name": ["Aman", "Saurav", "Karan", "Shubham", "Abhishek", None, "Sameer"],
    "Age": [22, 23, np.nan, 22, 25, 24, 26],
    "Marks": [85, np.nan, 88, 90, 56, 72, np.nan],
    "Subject": ["Math", "Physics", "Math", "Chemistry", "Math", "Physics", "Chemistry"]
}

In [30]:
# Task 1.1: Create the DataFrame
# Construct a Pandas DataFrame named df that replicates the "Raw Data" table shown in the previous cell. Use None or np.nan for missing values

df = pd.DataFrame(data)
print(df)

# Task 1.2: Basic Inspection
# Once created: 1. Check the shape of the dataset. 
# 2. Display the data types of the columns. 
# 3. Generate a statistical summary(mean/min/max) for the numericals column.

print("Shape of the dataset:", df.shape)  #this will print the shape of the DataFrame in the form of (number of rows, number of columns)
print("\nData types of the columns:\n", df.dtypes)  #this will print the data types of the columns in the DataFrame
print("\nStatistical summary of the numerical columns:\n", df.describe())  #this will print the statistical summary of the numerical columns

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
1    Saurav  23.0    NaN    Physics
2     Karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5       NaN  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry
Shape of the dataset: (7, 4)

Data types of the columns:
 Name           str
Age        float64
Marks      float64
Subject        str
dtype: object

Statistical summary of the numerical columns:
              Age      Marks
count   6.000000   5.000000
mean   23.666667  78.200000
std     1.632993  14.254824
min    22.000000  56.000000
25%    22.250000  72.000000
50%    23.500000  85.000000
75%    24.750000  88.000000
max    26.000000  90.000000

In [31]:
# Exercise 2: Selection & Aggregation
# Task: Filter and group the data. 
# 1.Selection: Create a view showing only the 'Name' and 'Marks' columns. 
df_selection = df[['Name', 'Marks']]
print(df_selection)

# 2.Filtering: Select students who scored above 80 marks. 
df_filtered = df[df['Marks'] > 80]
print(df_filtered)

# 3.Complex Filtering: Select students who are above 22 years of age and scored above 80 marks. 
df_complex_filtered = df[(df['Age'] > 22) & (df['Marks'] > 80)]
print(df_complex_filtered)

# 4.Aggregation: Count how many students are enrolled in each subject.
subject_count = df.groupby('Subject').size()
print(subject_count)

       Name  Marks
0      Aman   85.0
1    Saurav    NaN
2     Karan   88.0
3   Shubham   90.0
4  Abhishek   56.0
5       NaN   72.0
6    Sameer    NaN
      Name   Age  Marks    Subject
0     Aman  22.0   85.0       Math
2    Karan   NaN   88.0       Math
3  Shubham  22.0   90.0  Chemistry
Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []
Subject
Chemistry    2
Math         3
Physics      2
dtype: int64

In [32]:
# Exercise 3: Sorting & Ranking
# Task: Order the data to find rankers. 
# 1.Sort the DataFrame by 'Marks' in descending order. 
df_sorted = df.sort_values(by='Marks', ascending=False)
print(df_sorted)

# 2.Use a specific Pandas function to find the top 2 highest scorers (Scholorhip Candidates) without sorting the whole dataframe manually.
top_scorers = df.nlargest(2, 'Marks')
print(top_scorers)

# 3.Identify the student with the lowest marks (Remedial Candidate).
remedial_candidate = df.nsmallest(1, 'Marks')
print(remedial_candidate)

       Name   Age  Marks    Subject
3   Shubham  22.0   90.0  Chemistry
2     Karan   NaN   88.0       Math
0      Aman  22.0   85.0       Math
5       NaN  24.0   72.0    Physics
4  Abhishek  25.0   56.0       Math
1    Saurav  23.0    NaN    Physics
6    Sameer  26.0    NaN  Chemistry
      Name   Age  Marks    Subject
3  Shubham  22.0   90.0  Chemistry
2    Karan   NaN   88.0       Math
       Name   Age  Marks Subject
4  Abhishek  25.0   56.0    Math

In [33]:
# Exercise 4: Data Cleaning
# Task: Handle Missing Values
# 1. Calculate the total no. of missing values (Nan) in each column.
missing_values_count = df.isnull().sum()
print(missing_values_count)

# 2. Filter and display the rows where 'Marks' are missing.
missing_marks = df[df['Marks'].isnull()]
print(missing_marks)

# 3. Create a new dataframe called cleaned_df by removing any row that contains even a single missing value.
cleaned_df = df.dropna()
print(cleaned_df)

# 4. Compare the shape of cleaned_df vs original df.
print("Shape of original df:", df.shape)
print("Shape of cleaned_df:", cleaned_df.shape)

Name       1
Age        1
Marks      2
Subject    0
dtype: int64
     Name   Age  Marks    Subject
1  Saurav  23.0    NaN    Physics
6  Sameer  26.0    NaN  Chemistry
       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
Shape of original df: (7, 4)
Shape of cleaned_df: (3, 4)

In [34]:
# Exercise 5: Critical Thinking
# Task: Analyze the logic.
# 1. Technical Q: Look at the 'Marks' column in your uotput. Why are the values floats (e.g., 85.0) instead of integers?
#Answer- The values in the 'Marks' column are floats instead of integers because when a column contains missing values (NaN), Pandas automatically converts the entire column to a float data type to accommodate the NaN values. 
       # This is because NaN is considered a float in Pandas, and to maintain consistency in the data type of the column, all values are converted to floats.

# 2. Technical Q: What is the risk of using inplace=True when dropping rows with missing values?
#Answer- Using inplace=True modifies the original DataFrame directly, which can be risky because it makes it difficult to revert changes or debug issues. 
       # It's safer to create a new DataFrame with the cleaned data.

# 3. Bussiness Q: Based on the data, what specific feedback should you give to th eadmin team regarding the "Name" column?
#Answer- The "Name" column contains a missing value (None). I would recommend the admin team to ensure that all entries in the "Name" column are filled, as it is crucial for identifying students. 
       # They should implement data validation checks to prevent missing values in this column in the future.

GroupBy in Pandas

In [35]:
import pandas as pd
data={
    "Name": ["Aman", "Saurav", "Karan", "Shubham", "Abhishek", None, "Sameer"],
    "Age": [22, 23, None, 22, 25, 24, 26],
    "Marks": [85, None, 88, 90, 56, 72, None],
    "Subject": ["Math", "Physics", "Math", "Chemistry", "Math", "Physics", "Chemistry"]
}
df=pd.DataFrame(data)
print(df)

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
1    Saurav  23.0    NaN    Physics
2     Karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5       NaN  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry

In [36]:
# basic groupby
df.groupby('Subject')['Marks'].mean()  #this will group the DataFrame by the "Subject" column and calculate the mean of the "Marks" column for each group

Subject
Chemistry    90.000000
Math         76.333333
Physics      72.000000
Name: Marks, dtype: float64

In [37]:
df.groupby('Subject')['Name'].count() #this will group the DataFrame by the "Subject" column and count the number of non-null values in the "Name" column for each group

Subject
Chemistry    2
Math         3
Physics      1
Name: Name, dtype: int64

In [38]:
# Multiple Aggregations
df.groupby('Subject')['Marks'].agg(['mean', 'max', 'min'])  #this will group the DataFrame by the "Subject" column and calculate the mean, min and max of the "Marks" column for each group

                mean   max   min
Subject
Chemistry  90.000000  90.0  90.0
Math       76.333333  88.0  56.0
Physics    72.000000  72.0  72.0

In [39]:
df.groupby('Subject')['Marks'].agg(['mean', 'max', 'min', 'count'])  #this will group the DataFrame by the "Subject" column and calculate the mean, min, max and count of the "Marks" column for each group

                mean   max   min  count
Subject
Chemistry  90.000000  90.0  90.0      1
Math       76.333333  88.0  56.0      3
Physics    72.000000  72.0  72.0      1

In [40]:
# Group by Multiple Columns
df.groupby(['Subject', 'Age'])['Marks'].mean()  #this will group the DataFrame by both "Subject" and "Age" columns and calculate the mean of the "Marks" column for each group

Subject    Age
Chemistry  22.0    90.0
           26.0     NaN
Math       22.0    85.0
           25.0    56.0
Physics    23.0     NaN
           24.0    72.0
Name: Marks, dtype: float64